external:
  naver:
    pagination:
      size: 100  #max: 100, default: 10
    cafe:
      url: https://openapi.naver.com/v1/search/cafearticle.json
      clientId: WubhieoC0PbQRncZgofe
      clientSecret: tYAhfACYdU
  paxxo:
    pagination:
      size: 50
      limit: 100 #limited page count to be collected.
    country-maker-index-api: http://bike.passo.co.kr/bike/index.php?part=cybershop&path=cybershop&mode=process&process=country&idx=
    mode-index-api: http://bike.passo.co.kr/bike/index.php?part=cybershop&path=cybershop&mode=process&process=model&idx={0} # idx =maker id
    item-search-api: http://bike.passo.co.kr/bike/index.php
    item-url-pattern: http://bike.passo.co.kr/bike/index.php?part=cybershop&path=cybershop&mode=home#HIS_ID:search_mode=country&order_by=&num=0&idx={0} #idx =item idx

---
spring:
  profiles: local

elasticsearch:
  host: 127.0.0.1
  port: 9300
  clustername: elasticsearch_rikim

---
spring:
  profiles: test

external:
  paxxo:
    pagination:
      limit: 2

elasticsearch:
  host: 127.0.0.1
  port: 9300
  clustername: elasticsearch_rikim
